import type { Component } from 'vue';
import {
  AlarmClock,
  Bell,
  Briefcase,
  Calendar,
  CircleCheck,
  Coin,
  CreditCard,
  DataAnalysis,
  Document,
  DocumentAdd,
  DocumentChecked,
  DocumentCopy,
  EditPen,
  Files,
  Folder,
  FolderChecked,
  Help,
  InfoFilled,
  List,
  Location,
  Lock,
  MagicStick,
  Message,
  Money,
  More,
  Notebook,
  OfficeBuilding,
  Phone,
  Position,
  Postcard,
  Promotion,
  Reading,
  School,
  Search,
  Service,
  Stamp,
  Stopwatch,
  Tickets,
  Timer,
  User,
  UserFilled,
  Wallet,
  Warning,
  WarnTriangleFilled,
  Star
} from '@element-plus/icons-vue';

export interface MiniappIconOption {
  key: string;
  label: string;
  scene: string;
  component: Component;
}

export const MINIAPP_ICON_OPTIONS: MiniappIconOption[] = [
  { key: 'calculator', label: '计算器', component: MagicStick, scene: '计算工具' },
  { key: 'scale', label: '天平', component: Money, scene: '费用规则 法院收费' },
  { key: 'clipboard-list', label: '表单清单', component: List, scene: '流程清单' },
  { key: 'landmark', label: '机构', component: OfficeBuilding, scene: '法院 机构 管辖' },
  { key: 'hand-heart', label: '援助', component: Service, scene: '公益支持' },
  { key: 'file-text', label: '文书', component: Document, scene: '文书生成' },
  { key: 'shield-check', label: '复核', component: DocumentChecked, scene: '审核校验' },
  { key: 'folder-check', label: '材料整理', component: FolderChecked, scene: '材料归集' },
  { key: 'search-check', label: '查询', component: Search, scene: '检索核对' },
  { key: 'message-square', label: '咨询', component: Message, scene: '沟通咨询' },
  { key: 'more-horizontal', label: '更多', component: More, scene: '更多入口' },
  { key: 'calendar-days', label: '日期', component: Calendar, scene: '日期推算 期间' },
  { key: 'calendar-check', label: '年假', component: Calendar, scene: '劳动 年休假' },
  { key: 'badge-dollar-sign', label: '金额', component: Money, scene: '金额 费用 薪资' },
  { key: 'timer-reset', label: '计时', component: Timer, scene: '延迟履行 计时' },
  { key: 'file-check-2', label: '文本核对', component: DocumentChecked, scene: '示范文本 核对' },
  { key: 'book-open', label: '法规阅读', component: Reading, scene: '法规 条文' },
  { key: 'book-open-check', label: '规则核对', component: Reading, scene: '规则 核验' },
  { key: 'book-marked', label: '条文收藏', component: Notebook, scene: '收藏 条文' },
  { key: 'file-search', label: '文档检索', component: Search, scene: '文档 检索' },
  { key: 'file-plus-2', label: '新增材料', component: DocumentAdd, scene: '新增 材料' },
  { key: 'file-pen-line', label: '文书编辑', component: EditPen, scene: '编辑 文书' },
  { key: 'file-lock-2', label: '保密材料', component: Lock, scene: '保密 材料' },
  { key: 'files', label: '文件组', component: Files, scene: '文件 批量' },
  { key: 'folder-search', label: '材料检索', component: Folder, scene: '材料 检索' },
  { key: 'list-checks', label: '核对清单', component: CircleCheck, scene: '清单 核对' },
  { key: 'clipboard-check', label: '已核对', component: DocumentChecked, scene: '核对 完成' },
  { key: 'clipboard-pen-line', label: '填写表单', component: EditPen, scene: '表单 填写' },
  { key: 'clipboard-signature', label: '签署', component: EditPen, scene: '签署 确认' },
  { key: 'circle-help', label: '帮助', component: Help, scene: '帮助 指引' },
  { key: 'info', label: '说明', component: InfoFilled, scene: '说明 信息' },
  { key: 'megaphone', label: '公告', component: Promotion, scene: '公告 通知' },
  { key: 'bell', label: '提醒', component: Bell, scene: '提醒 通知' },
  { key: 'send', label: '提交', component: Position, scene: '提交 发送' },
  { key: 'phone-call', label: '电话', component: Phone, scene: '电话 联系' },
  { key: 'mail', label: '邮件', component: Message, scene: '邮件 通知' },
  { key: 'map-pin', label: '地址', component: Location, scene: '地址 地点' },
  { key: 'building-2', label: '单位', component: OfficeBuilding, scene: '单位 机构' },
  { key: 'gavel', label: '法槌', component: Stamp, scene: '法院 法官 裁判' },
  { key: 'scroll-text', label: '卷宗', component: Tickets, scene: '卷宗 文书 案件' },
  { key: 'receipt-text', label: '票据', component: Postcard, scene: '票据 收费 凭证' },
  { key: 'wallet-cards', label: '账户', component: Wallet, scene: '账户 钱包' },
  { key: 'coins', label: '款项', component: Coin, scene: '款项 金额' },
  { key: 'badge-percent', label: '利率', component: DataAnalysis, scene: '利率 百分比' },
  { key: 'chart-column', label: '统计', component: DataAnalysis, scene: '统计 图表' },
  { key: 'calendar-clock', label: '期间', component: AlarmClock, scene: '期间 时间' },
  { key: 'calendar-plus', label: '日期新增', component: Calendar, scene: '日期 新增' },
  { key: 'clock-3', label: '时间', component: AlarmClock, scene: '时间 时点' },
  { key: 'hourglass', label: '期限', component: Stopwatch, scene: '期限 倒计时' },
  { key: 'users', label: '多人', component: User, scene: '多人 当事人' },
  { key: 'user-check', label: '身份核对', component: UserFilled, scene: '身份 核对' },
  { key: 'user-round-check', label: '用户认证', component: UserFilled, scene: '用户 认证' },
  { key: 'briefcase-business', label: '业务', component: Briefcase, scene: '业务 服务' },
  { key: 'shield-alert', label: '风险防护', component: Warning, scene: '风险 防护' },
  { key: 'triangle-alert', label: '风险提示', component: WarnTriangleFilled, scene: '风险 提示' },
  { key: 'circle-alert', label: '注意事项', component: Warning, scene: '注意事项' },
  { key: 'file-clock', label: '生成记录', component: DocumentCopy, scene: '记录 历史' },
  { key: 'star', label: '收藏', component: Star, scene: '收藏 标记' },
  { key: 'school', label: '学堂', component: School, scene: '学习 指引' },
  { key: 'credit-card', label: '卡片', component: CreditCard, scene: '卡片 支付' }
];

export function findMiniappIconOption(iconKey: string) {
  return MINIAPP_ICON_OPTIONS.find((item) => item.key === iconKey);
}
